export const REGISTER_ERROR = 'REGISTER_ERROR'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const CLEAR_REGISTER_ERROR = 'CLEAR_REGISTER_ERROR'
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR'

export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'
